title: Pixel Power Podcast
logo: /assets/img/logo.png
description: 'The podcast that helps you get the most out of your Google-powered devices.'
show_downloads: false
google_analytics: 
theme: jekyll-theme-minimal
timezone: America/Indiana/Indianapolis
