title: Pixel Power Podcast
logo: /assets/img/logo.svg
url: https://www.pixelpowerpodcast.com
description: 'Each episode and post helps you get the most out of your Google-powered devices and apps.'
show_downloads: true
google_analytics: UA-129766303-1
theme: jekyll-theme-minimal
timezone: America/Indiana/Indianapolis
author: Steven B. Combs, Ph.D.
